---
name: postee-ui
on:
  push:
    branches: [main]
    paths:
      - 'ui/**'    
  pull_request:
    branches: [main]
  workflow_dispatch:    
env:
  GO_VERSION: "1.18"

jobs:
  build:
    name: Checks
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          args: --timeout=10m --verbose
          version: v1.45

      - name: Docker-compose
        run: make composer


